// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gpio.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum PBGpio_GpioPin: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case pc0 // = 0
  case pc1 // = 1
  case pc3 // = 2
  case pb2 // = 3
  case pb3 // = 4
  case pa4 // = 5
  case pa6 // = 6
  case pa7 // = 7
  case UNRECOGNIZED(Int)

  init() {
    self = .pc0
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .pc0
    case 1: self = .pc1
    case 2: self = .pc3
    case 3: self = .pb2
    case 4: self = .pb3
    case 5: self = .pa4
    case 6: self = .pa6
    case 7: self = .pa7
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .pc0: return 0
    case .pc1: return 1
    case .pc3: return 2
    case .pb2: return 3
    case .pb3: return 4
    case .pa4: return 5
    case .pa6: return 6
    case .pa7: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension PBGpio_GpioPin: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [PBGpio_GpioPin] = [
    .pc0,
    .pc1,
    .pc3,
    .pb2,
    .pb3,
    .pa4,
    .pa6,
    .pa7,
  ]
}

#endif  // swift(>=4.2)

enum PBGpio_GpioPinMode: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case output // = 0
  case input // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .output
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .output
    case 1: self = .input
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .output: return 0
    case .input: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension PBGpio_GpioPinMode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [PBGpio_GpioPinMode] = [
    .output,
    .input,
  ]
}

#endif  // swift(>=4.2)

enum PBGpio_GpioInputPull: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case no // = 0
  case up // = 1
  case down // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .no
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .no
    case 1: self = .up
    case 2: self = .down
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .no: return 0
    case .up: return 1
    case .down: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension PBGpio_GpioInputPull: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [PBGpio_GpioInputPull] = [
    .no,
    .up,
    .down,
  ]
}

#endif  // swift(>=4.2)

struct PBGpio_SetPinMode {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pin: PBGpio_GpioPin = .pc0

  var mode: PBGpio_GpioPinMode = .output

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_SetInputPull {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pin: PBGpio_GpioPin = .pc0

  var pullMode: PBGpio_GpioInputPull = .no

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_GetPinMode {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pin: PBGpio_GpioPin = .pc0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_GetPinModeResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mode: PBGpio_GpioPinMode = .output

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_ReadPin {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pin: PBGpio_GpioPin = .pc0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_ReadPinResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct PBGpio_WritePin {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pin: PBGpio_GpioPin = .pc0

  var value: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension PBGpio_GpioPin: @unchecked Sendable {}
extension PBGpio_GpioPinMode: @unchecked Sendable {}
extension PBGpio_GpioInputPull: @unchecked Sendable {}
extension PBGpio_SetPinMode: @unchecked Sendable {}
extension PBGpio_SetInputPull: @unchecked Sendable {}
extension PBGpio_GetPinMode: @unchecked Sendable {}
extension PBGpio_GetPinModeResponse: @unchecked Sendable {}
extension PBGpio_ReadPin: @unchecked Sendable {}
extension PBGpio_ReadPinResponse: @unchecked Sendable {}
extension PBGpio_WritePin: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "PB_Gpio"

extension PBGpio_GpioPin: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PC0"),
    1: .same(proto: "PC1"),
    2: .same(proto: "PC3"),
    3: .same(proto: "PB2"),
    4: .same(proto: "PB3"),
    5: .same(proto: "PA4"),
    6: .same(proto: "PA6"),
    7: .same(proto: "PA7"),
  ]
}

extension PBGpio_GpioPinMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OUTPUT"),
    1: .same(proto: "INPUT"),
  ]
}

extension PBGpio_GpioInputPull: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO"),
    1: .same(proto: "UP"),
    2: .same(proto: "DOWN"),
  ]
}

extension PBGpio_SetPinMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetPinMode"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pin"),
    2: .same(proto: "mode"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pin != .pc0 {
      try visitor.visitSingularEnumField(value: self.pin, fieldNumber: 1)
    }
    if self.mode != .output {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_SetPinMode, rhs: PBGpio_SetPinMode) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_SetInputPull: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetInputPull"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pin"),
    2: .standard(proto: "pull_mode"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.pullMode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pin != .pc0 {
      try visitor.visitSingularEnumField(value: self.pin, fieldNumber: 1)
    }
    if self.pullMode != .no {
      try visitor.visitSingularEnumField(value: self.pullMode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_SetInputPull, rhs: PBGpio_SetInputPull) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.pullMode != rhs.pullMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_GetPinMode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetPinMode"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pin"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pin) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pin != .pc0 {
      try visitor.visitSingularEnumField(value: self.pin, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_GetPinMode, rhs: PBGpio_GetPinMode) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_GetPinModeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetPinModeResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "mode"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != .output {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_GetPinModeResponse, rhs: PBGpio_GetPinModeResponse) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_ReadPin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReadPin"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pin"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pin) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pin != .pc0 {
      try visitor.visitSingularEnumField(value: self.pin, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_ReadPin, rhs: PBGpio_ReadPin) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_ReadPinResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReadPinResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != 0 {
      try visitor.visitSingularUInt32Field(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_ReadPinResponse, rhs: PBGpio_ReadPinResponse) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBGpio_WritePin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WritePin"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "pin"),
    2: .same(proto: "value"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pin != .pc0 {
      try visitor.visitSingularEnumField(value: self.pin, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt32Field(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBGpio_WritePin, rhs: PBGpio_WritePin) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
