schemaVersion: 1

enabledWorkflows:
  - simulator
  - simulator-management
  - swift-package
  - ui-automation
  - logging
  - coverage
  - project-discovery
  - xcode-ide

disableSessionDefaults: false
activeSessionDefaultsProfile: ios
sessionDefaultsProfiles:
  ios:
    projectPath: "./Flipper/Flipper.xcodeproj"
    scheme: "Flipper(iOS)"
    configuration: "Debug"
    simulatorName: "iPhone 17 Pro"
    simulatorPlatform: "iOS Simulator"
    useLatestOS: true

incrementalBuildsEnabled: false
debug: false
sentryDisabled: true
